# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0

# Draw geometry:
/vis/drawVolume

# Specify style (surface, wireframe, auxiliary edges,cloud...)
/vis/viewer/set/style surface
/vis/viewer/set/lineSegmentsPerCircle 17

/vis/ASCIITree/verbose 5
/vis/drawTree

# Draw smooth trajectories at end of event
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID

# Accumulate trajectories for each event
/vis/scene/endOfEventAction accumulate

# Make the "world_volume" box invisible
/vis/geometry/set/visibility world_volume 0 false
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

/vis/scene/add/axes

#/control/execute gun.mac
